name: README pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Generate README file
        run: go run .
